app:
    resource: '@AppBundle/Controller/'
    type: annotation

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /manager

home:
    path: /
    controller : AppBundle\Controller\Front\HomeController::indexAction

panel:
    path: /panel
    controller : AppBundle\Controller\Panel\HomeController:indexAction



panel.get.skills:
    path: /panel/skills
    controller : Appbundle\Controller\Panel\SkillsController:indexAction
    methods: [GET]

panel.delete.skills:
    path: /panel/skills/{id}
    controller: AppBundle\Controller\Panel\SkillsController:deleteAction
    methods: [DELETE]

panel.update.skills:
    path: /panel/skills/{id}
    controller: AppBundle\Controller\Panel\SkillsController:updateAction
    methods: [PUT , PATCH]

panel.store.skills:
    path: /panel/skills
    controller: AppBundle\Controller\Panel\SkillsController:storeAction
    methods: [POST]

panel.create.skills:
    path: /panel/create
    controller: AppBundle\Controller\Panel\SkillsController:createAction
    methods: [GET]

panel.edit.skills:
    path: /panel/skills/{id}/edit
    controller: AppBundle\Controller\Panel\SkillsController:editAction
    methods: [GET]

